# Generated by Django 2.2.7 on 2019-12-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anketgonder', '0004_auto_20191218_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anket',
            name='islem_tarihi',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
