# Generated by Django 2.2.7 on 2020-01-05 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anketgonder', '0006_cevaplar'),
    ]

    operations = [
        migrations.AddField(
            model_name='cevaplar',
            name='deger',
            field=models.CharField(choices=[(1, 'Çok Kötü'), ('2', 'Kötü'), (3, 'Orta'), (4, 'İyi'), (5, 'Çok İyi')], default=None, max_length=30),
        ),
    ]
