# Generated by Django 2.2.7 on 2020-01-05 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anketgonder', '0007_cevaplar_deger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cevaplar',
            name='deger',
            field=models.IntegerField(choices=[(1, 'Çok Kötü'), (2, 'Kötü'), (3, 'Orta'), (4, 'İyi'), (5, 'Çok İyi')], default=None, max_length=30),
        ),
    ]
