# Generated by Django 2.2.7 on 2020-01-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anket', '__first__'),
        ('anketgonder', '0009_auto_20200105_0337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cevaplar',
            name='anket_soru_id',
        ),
        migrations.AddField(
            model_name='cevaplar',
            name='anket_soru_id',
            field=models.ManyToManyField(to='anket.Sorular'),
        ),
    ]
