# Generated by Django 2.2.5 on 2019-09-13 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UyeKurumlar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unvan', models.CharField(max_length=250)),
                ('iletisim_no', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=50)),
                ('puan', models.IntegerField()),
                ('islem_tarihi', models.DateTimeField()),
                ('kullanici_adi', models.CharField(max_length=50)),
            ],
        ),
    ]
