# Generated by Django 2.2.5 on 2019-09-13 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sorular',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('soru_baslik', models.CharField(max_length=250, verbose_name='Soru Grubu')),
                ('soru_icerik', models.TextField(verbose_name='Soru İçerik')),
                ('cevap', models.IntegerField()),
                ('islem_tarihi', models.DateTimeField()),
                ('kullanici_adi', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='uyekurumlar',
            name='unvan',
            field=models.CharField(max_length=250, verbose_name='İş Yeri Ünvanı'),
        ),
    ]
