# Generated by Django 2.2.7 on 2020-02-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isciler',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='kurumlar',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='yoneticiler',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='E-mail'),
        ),
    ]
