# Generated by Django 2.2.5 on 2019-10-05 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anket', '0003_auto_20191006_0030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yoneticiler',
            old_name='baglioldugu_kurum',
            new_name='kurum_kod',
        ),
    ]
